### ISSUE TITLE
The defination of 10-shot

### ISSUE THREAD

**Issue by wcy1122** [ptx9363/BCNet#3]
Thanks for your outstanding works first.

Here is a question about the defination of 10-shot.
I think every images shoud have access to 10 images for each class. 
Your "trainval10shot.txt" files contain 200 different images, and some of which images contain more than 1 class. And your code use all these gt-bboxes in the 200 images.
So in this way some class may have access to more than 10 images.

Thanks.

**Comment by ptx9363** [comment]
Yes, you are right. We did this because limiting the number of object for each class is too difficult and manually selecting images is unfair to evaluate different semi-supervised methods.
In fact, the term "10shot" here is acutally indicating 10-15 object for each class.  As a sequence, to fairly evaluate previous semi-supervised methods, you have to use the same train/test split and that's why we share our split here.

By the way, we found about 1.5-3 objects in average for each class.

**Comment by wcy1122** [comment]
Ok.
Thanks for your reply and thanks for providing these train/test splits.
